### ISSUE TITLE
RPi Desktop version for Pi4 emulation?

### ISSUE THREAD

**Issue by Bukkster** [Qengineering/RPi-image#1]
Hey there,
Thank you for all the hard work you put into this and the documentation.
I'm trying to emulate my RPi4 on my windows 10 desktop and am wondering if is there a .iso version of this that I could run as a virtual machine using Hyper-V or VirtualBox? Should I try to do it the [qemu way](https://dominoc925.blogspot.com/2019/09/how-to-emulate-raspbian-os-in-qemu-on.html) or find a way to convert your RPi_64OS_DNN.img to .iso then mount use virtualbox (worried the difference in arm and amd architectures for the compiled software)?

**Comment by Qengineering** [comment]
I'm sorry @Bukkster, there is no ISO version you can run on Windows computer.
The only way I can think of is by manually installing different frameworks and software.

**Comment by Bukkster** [comment]
Dang that's a bummer, thanks for the quick response!
