### ISSUE TITLE
Installation on raspberry Pi 3b

### ISSUE THREAD

**Issue by Learner00100** [Qengineering/RPi-image#17]
Can this image can be installed on raspberry Pi 3b?

**Comment by Qengineering** [comment]
Unfortunately not. It's only suitable for the Raspberry Pi 4

**Comment by Learner00100** [comment]
@Qengineering thanks for quick reply.

I am struggling in installing tensorflow add-on on raspberry Pi 3b.

In latest bullseye 64bit with python 3.9.3, I installed tensorflow wheel given in drive and it's installed successfully but while installing tensorflow addon 0.14(which is linked with tensor flow 2.5) as mentioned in tutorial, i am getting wheel not supported on this platform error.

I also tried with old buster os.zip in your website and tried install tensorflow but getting some HDF5 error.

Can you please guide me any proper way to get tensorflow addon on raspberry Pi 3b.

Also can confirm whether the below code works on your rpi image with dnn
https://gist.github.com/fyr91/79aaf4b6d679814406ee4028bd03b7aa
Source:
https://towardsdatascience.com/real-time-face-recognition-with-cpu-983d35cc3ec5
