### ISSUE TITLE
help updating ncnn benchmark data on raspberrypi

### ISSUE THREAD

**Issue by nihui** [Qengineering/RPi-image#9]
hi

The raspberrypi 4 data in ncnn benchmark is very old[0], and the latest ncnn is faster than before.

I've tested ncnn on raspberrypi 3b+ and got new benchmark data [1]

But I have no other raspberrypi devices for updating info.

Could you please help updating them ?

[0] https://github.com/Tencent/ncnn/blob/master/benchmark/README.md#raspberry-pi-4-model-b-broadcom-bcm2711b0-cortex-a72-armv8-15ghz-x-4
[1] https://github.com/Tencent/ncnn/blob/master/benchmark/README.md#raspberry-pi-3-model-b-broadcom-bcm2837b0-cortex-a53-armv8-14ghz-x-4

## step 1 shutdown graphics stack
on Linux (with root)
```
init 3
```
or
```
systemctl isolate multi-user.target
```

on Android (with root)
```
adb root
adb shell stop
```

## step 2 set cpu performance mode
on Linux / Android (with root)
```
echo "performance" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo "performance" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
echo "performance" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
echo "performance" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
```

## step 3 git clone the latest ncnn source, build benchncnn, and run
```
git clone https://github.com/Tencent/ncnn.git
cd ncnn
mkdir build && cd build
cmake ..
make -j4 benchncnn
```

benchmark with 4 threads
```
./benchncnn 8 4 0 -1 1
```

benchmark with 1 thread
```
./benchncnn 4 1 0 -1 1
```

## step 4 (optional) restore graphics stack
on Linux (with root)
```
init 5
```
or
```
systemctl isolate graphical.target
```

on Android (with root)
```
adb root
adb shell start
```

## step 5 collect benchmark data and open pull request to ncnn project :smile: 

Thanks!

**Comment by Qengineering** [comment]
Halfway

**Comment by Qengineering** [comment]
Done. Sorry, wrong button. I didn't made a pull request but a [issue](https://github.com/Tencent/ncnn/issues/3485).

**Comment by nihui** [comment]
Thanks !
I will investigate the jetson nano crash you mentioned

**Comment by nihui** [comment]
I have updated the ncnn benchmark data

btw, in https://github.com/nihui/ncnn-small-board too
